#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Each layer gets a name for readability, which is then used in the keymap matrix below.
// The underscores don't mean anything - you can have a layer called STUFF or any other name.
// Layer names don't all need to be of the same length, obviously, and you can also skip them
// entirely and just use numbers.
enum layers {
    _DVORAK,
    _SYMBOL,
    _NAV,
    _NUMERIC,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_DVORAK] = LAYOUT_split_3x6_3(KC_NO, KC_QUOT, KC_COMM, KC_DOT, LCTL_T(KC_P), KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_NO, KC_NO, LGUI_T(KC_A), LALT_T(KC_O), LCTL_T(KC_E), LSFT_T(KC_U), LT(3,KC_I), KC_D, KC_H, KC_T, KC_N, KC_S, KC_NO, KC_NO, LSFT_T(KC_SCLN), KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, RSFT_T(KC_Z), KC_NO, LCTL_T(KC_ESC), LT(3,KC_TAB), LT(2,KC_SPC), KC_ENT, LT(1,KC_BSPC), LALT_T(KC_DEL)),


	[_SYMBOL] = LAYOUT_split_3x6_3(KC_NO, KC_GRV, KC_CIRC, KC_AT, KC_DLR, KC_TILD, KC_AMPR, KC_EXLM, KC_PIPE, KC_UNDS, KC_HASH, KC_NO, KC_NO, KC_SLSH, KC_LBRC, KC_LCBR, KC_LPRN, KC_EQL, KC_ASTR, KC_RPRN, KC_RCBR, KC_RBRC, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_QUES, KC_PLUS, KC_PERC, KC_MINS, KC_PSCR, KC_NO, KC_MINS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT),


	[_NAV] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGDN, KC_UP, KC_PGUP, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),


	[_NUMERIC] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_F9, KC_F10, KC_F5, KC_F12, KC_PLUS, KC_7, KC_8, KC_9, KC_SLSH, KC_NO, KC_NO, KC_NO, KC_F5, KC_F6, KC_F2, KC_F8, KC_0, KC_4, KC_5, KC_6, KC_DOT, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_MINS, KC_1, KC_2, KC_3, KC_ASTR, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





