#define BASE_1_1 LT(_ART_SYM,KC_A)
#define BASE_1_2 KC_R
#define BASE_1_3 KC_T
#define BASE_1_4 LT(_ART_NUM,KC_S)
#define BASE_2_1 LT(_ART_PUNC,KC_E)
#define BASE_2_2 KC_Y
#define BASE_2_3 KC_I
#define BASE_2_4 LT(_ART_CUS,KC_O)
#define NUM_1_1 KC_1
#define NUM_1_2 KC_2
#define NUM_1_3 KC_3
#define NUM_1_4 KC_TRNS
#define NUM_2_1 KC_4
#define NUM_2_2 KC_5
#define NUM_2_3 KC_6
#define NUM_2_4 KC_TRNS
#define PUNC_1_1 KC_HASH
#define PUNC_1_2 KC_GRV
#define PUNC_1_3 KC_SCLN
#define PUNC_1_4 KC_BSLS
#define PUNC_2_1 KC_TRNS
#define PUNC_2_2 KC_AT
#define PUNC_2_3 KC_MINS
#define PUNC_2_4 KC_EQL
#define CUS_1_1 KC_MPLY
#define CUS_1_2 KC_MUTE
#define CUS_1_3 KC_VOLU
#define CUS_1_4 KC_TRNS
#define CUS_2_1 KC_MPRV
#define CUS_2_2 KC_MNXT
#define CUS_2_3 KC_VOLD
#define CUS_2_4 KC_TRNS
#define SYM_1_1 KC_TRNS
#define SYM_1_2 KC_LPRN
#define SYM_1_3 KC_LBRC
#define SYM_1_4 KC_LCBR
#define SYM_2_1 KC_TRNS
#define SYM_2_2 KC_RPRN
#define SYM_2_3 KC_RBRC
#define SYM_2_4 KC_RCBR
#define MOU_1_1 MS_BTN1
#define MOU_1_2 MS_UP
#define MOU_1_3 MS_BTN2
#define MOU_1_4 MS_WHLU
#define MOU_2_1 MS_LEFT
#define MOU_2_2 MS_DOWN
#define MOU_2_3 MS_RGHT
#define MOU_2_4 MS_WHLD
#define NAV_1_1 KC_HOME
#define NAV_1_2 KC_UP
#define NAV_1_3 KC_END
#define NAV_1_4 KC_PGUP
#define NAV_2_1 KC_LEFT
#define NAV_2_2 KC_DOWN
#define NAV_2_3 KC_RIGHT
#define NAV_2_4 KC_PGDN